# Generated by Django 4.2.10 on 2024-09-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='title',
            field=models.CharField(default='Random task', max_length=40),
        ),
    ]
