# Generated by Django 4.2.10 on 2024-09-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0002_todolist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
