# Generated by Django 4.2.16 on 2024-10-23 17:36

import django.core.validators
from django.db import migrations, models
import tasty_recipes_app.profiles.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Nickname must be at least 2 chars long!')])),
                ('first_name', models.CharField(max_length=30, validators=[tasty_recipes_app.profiles.validators.UpperValueValidator()])),
                ('last_name', models.CharField(max_length=30, validators=[tasty_recipes_app.profiles.validators.UpperValueValidator()])),
                ('chef', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
