# Generated by Django 4.2.16 on 2024-10-27 12:11

from django.db import migrations, models
import final_exam.authors.validators


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='passcode',
            field=models.CharField(help_text='Your passcode must be a combination of 6 digits', validators=[final_exam.authors.validators.ExactSixDigitsValidator()]),
        ),
    ]
