# Generated by Django 4.2.16 on 2024-10-25 20:04

import django.core.validators
from django.db import migrations, models
import my_plant_app.profiles.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=20, validators=[my_plant_app.profiles.validators.StartsWithValidator()])),
                ('last_name', models.CharField(validators=[my_plant_app.profiles.validators.StartsWithValidator()])),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
